### ISSUE TITLE
Outline colors

### ISSUE THREAD

**Issue by Faridabdallah01** [rewindui/rewindui#51]
Hello,

I'm having difficulty changing the outline color of the inputs when they are active. Is there a way to achieve this?

Thank you in advance.

![image](https://github.com/rewindui/rewindui/assets/102731189/ed9937b2-949c-499e-b632-16e94ea85888)

**Comment by NickDunas** [comment]
Hello,

To change the ring & border color you will have to update the Input.styles.ts file as shown on the theming section of the documentation: https://rewind-ui.dev/theming

Looks like though that this is highly requested from other developers that reached out as well, so I am about to add a new color property to all form elements to avoid having to use the theme provider just for that.

I will reply back to you on this issue once I push the update, so that you can test it out.

**Comment by NickDunas** [comment]
Hello again Farid. Please try installing version 0.9.2

I have added a color prop on all form components and have set the default to dark as I thought that purple was too opinionated and decided to choose a more neutral default.

Let me know if you have any further questions/considerations!

**Comment by Faridabdallah01** [comment]
It's great! Thank you very much for your promptness. It's perfect now!
